# Generated by Django 5.0 on 2024-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='accounts', to='books.book'),
        ),
    ]
