# Generated by Django 5.0 on 2024-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_book'),
        ('books', '0002_book_author_alter_book_image_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='books.book'),
        ),
    ]
