# Generated by Django 5.0 on 2024-01-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
