# Generated by Django 5.0 on 2024-01-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_borrow_returning_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
