# Generated by Django 5.0 on 2024-01-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_borrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
